# Generated by Django 5.1.1 on 2025-01-07 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the task title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Enter the task description (optional)', null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the task was created')),
                ('completed', models.BooleanField(default=False, help_text='Whether the task is completed')),
                ('due_date', models.DateField(blank=True, help_text='Date when the task is due (optional)', null=True)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1, help_text='Priority of the task (1-3)')),
            ],
            options={
                'ordering': ['-priority', '-due_date', '-created_date'],
            },
        ),
    ]
